export const fonts = {
  MacPawFixelDisplayBold: 'MacPawFixelDisplay-Bold',
  MacPawFixelDisplayExtraBold: 'MacPawFixelDisplay-ExtraBold',
  MacPawFixelDisplayLight: 'MacPawFixelDisplay-Light',
  MacPawFixelDisplayMedium: 'MacPawFixelDisplay-Medium',
  MacPawFixelDisplayRegular: 'MacPawFixelDisplay-Regular',
  MacPawFixelDisplaySemiBold: 'MacPawFixelDisplay-SemiBold',
  MacPawFixelDisplayThin: 'MacPawFixelDisplay-Thin',
  SFProDisplayBlack: 'SF-Pro-Display-Black',
  SFProDisplayBlackItalic: 'SF-Pro-Display-BlackItalic',
  SFProDisplayBold: 'SF-Pro-Display-Bold',
  SFProDisplayBoldItalic: 'SF-Pro-Display-BoldItalic',
  SFProDisplayHeavy: 'SF-Pro-Display-Heavy',
  SFProDisplayHeavyItalic: 'SF-Pro-Display-HeavyItalic',
  SFProDisplayLight: 'SF-Pro-Display-Light',
  SFProDisplayLightItalic: 'SF-Pro-Display-LightItalic',
  SFProDisplayMedium: 'SF-Pro-Display-Medium',
  SFProDisplayMediumItalic: 'SF-Pro-Display-MediumItalic',
  SFProDisplayRegular: 'SF-Pro-Display-Regular',
  SFProDisplayRegularItalic: 'SF-Pro-Display-RegularItalic',
  SFProDisplaySemibold: 'SF-Pro-Display-Semibold',
  SFProDisplaySemiboldItalic: 'SF-Pro-Display-SemiboldItalic',
  SFProDisplayThin: 'SF-Pro-Display-Thin',
  SFProDisplayThinItalic: 'SF-Pro-Display-ThinItalic',
  SFProDisplayUltralight: 'SF-Pro-Display-Ultralight',
  SFProDisplayUltralightItalic: 'SF-Pro-Display-UltralightItalic',
};
